baseURL = "https://www.example.com/"
languageCode = "es-ES"
title = "Climaton SVQ"
themesDir = "themes"
theme = "hero"
enableEmoji = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/home_icon.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo_01.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Climathon Sevilla"

  [params.homepage_meta_tags]
    meta_description = "Climathon Description"
    meta_og_title = "Hugo Hero Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Climathon Description"
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "Colabora"
	url = "/services/"
    weight = 1

# [[menu.main]]
#    name = "2022"
#    url = "/work/"
#    weight = 2

[[menu.main]]
    name = "Participa"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Ediciones Anteriores"
    url = "/about/"
    weight = 3


[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
